#!/usr/bin/env python3
"""Generate a Path B stress plugin config (gzip+base64) for configure-stress.

Emits many setvar score rules, a deny chain (CRS 949111-like), and an isolated
@pmFromFile rule so msc_rules_add exercises the same peak paths that forced
INITIAL_MEMORY to 128MB. Does not embed full CRS confs (path-b catalog).
"""

from __future__ import annotations

import argparse
import base64
import gzip
import json
import sys
from pathlib import Path


def build_directives(n_score_rules: int) -> list[str]:
    lines: list[str] = [
        "Include @kubewaf-defaults",
        "SecRuleEngine On",
        "SecDebugLogLevel 0",
        # Isolated phrase-file operator (loads catalog .data automata alone).
        (
            'SecRule REQUEST_HEADERS:User-Agent '
            '"@pmFromFile scanners-user-agents.data" '
            '"id:913100,phase:1,pass,nolog,t:none,'
            "setvar:'tx.anomaly_score_pl1=+5'\""
        ),
    ]
    # Many small setvar rules — historically trapped V8 when batched with chains.
    for i in range(n_score_rules):
        rid = 900100 + i
        lines.append(
            f'SecRule ARGS "@rx stress-token-{i}" '
            f'"id:{rid},phase:2,pass,nolog,t:none,'
            f"setvar:'tx.anomaly_score_pl1=+1'\""
        )
    # Chained deny (parent + child must stay in one msc_rules_add chunk).
    # Disruptive action only on the chain starter (ModSecurity rule).
    lines.append(
        'SecRule TX:ANOMALY_SCORE "@ge 5" '
        '"id:949110,phase:2,deny,status:403,log,msg:\'stress anomaly\','
        'chain"'
    )
    lines.append('SecRule TX:ANOMALY_SCORE "@gt 0" "t:none"')
    # Extra bulk to force multi-chunk loads at 4KB isolation.
    for i in range(n_score_rules // 2):
        rid = 910000 + i
        lines.append(
            f'SecRule REQUEST_HEADERS "@rx hdr-stress-{i}" '
            f'"id:{rid},phase:1,pass,nolog,t:none"'
        )
    return lines


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--score-rules",
        type=int,
        default=120,
        help="Number of synthetic setvar score SecRules (default: 120)",
    )
    ap.add_argument(
        "--out-json",
        type=Path,
        help="Write plugin configuration JSON (gzip+base64 directives_map)",
    )
    ap.add_argument(
        "--out-envoy",
        type=Path,
        help="Write full Envoy YAML embedding the plugin JSON",
    )
    ap.add_argument(
        "--plain",
        action="store_true",
        help="Use plain JSON array instead of gzip+base64 (debug)",
    )
    args = ap.parse_args()

    directives = build_directives(args.score_rules)
    if args.plain:
        plugin = {
            "directives_map": {"default": directives},
            "default_directives": "default",
            "metric_labels": {
                "owner": "modsecurity-proxy-wasm",
                "identifier": "configure-stress",
            },
            "metrics": {
                "enabled": True,
                "per_rule_id": False,
                "rule_tags": False,
                "dual_prefix": False,
            },
        }
    else:
        joined = "\n".join(directives) + "\n"
        compressed = gzip.compress(joined.encode("utf-8"), mtime=0)
        b64 = base64.b64encode(compressed).decode("ascii")
        plugin = {
            "directives_encoding": "gzip+base64",
            "directives_map": {"default": b64},
            "default_directives": "default",
            "directives_stats": {
                "raw_bytes": len(joined),
                "compressed_bytes": len(compressed),
                "score_rules": args.score_rules,
            },
            "metric_labels": {
                "owner": "modsecurity-proxy-wasm",
                "identifier": "configure-stress",
            },
            "metrics": {
                "enabled": True,
                "per_rule_id": False,
                "rule_tags": False,
                "dual_prefix": False,
            },
        }

    plugin_json = json.dumps(plugin, indent=2)
    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(plugin_json + "\n", encoding="utf-8")
        print(
            f"Wrote plugin JSON ({len(plugin_json)} bytes, "
            f"{len(directives)} directives) -> {args.out_json}",
            file=sys.stderr,
        )

    if args.out_envoy:
        # Indent plugin JSON for embedding under | block scalar.
        indented = "\n".join("                    " + line for line in plugin_json.splitlines())
        yaml = f"""# Generated by generate-configure-stress-config.py — do not edit by hand.
# Path B configure stress: gzip directives + chains + @pmFromFile.
stats_config:
  stats_tags:
    - tag_name: phase
      regex: "(_phase=(http_request_headers|http_request_body|http_response_headers|http_response_body|http_logging|unknown))"
    - tag_name: owner
      regex: "(_owner=([0-9a-z.:_-]+?))(?:_|$)"
    - tag_name: identifier
      regex: "(_identifier=([0-9a-z.:_-]+))"

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_backend
          http_filters:
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                name: "modsecurity_proxy_wasm"
                vm_config:
                  vm_id: "modsecurity_proxy_wasm_configure_stress"
                  runtime: "envoy.wasm.runtime.v8"
                  code:
                    local:
                      filename: "/etc/modsecurity-proxy-wasm.wasm"
                configuration:
                  "@type": "type.googleapis.com/google.protobuf.StringValue"
                  value: |
{indented}
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  - name: backend_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 19000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: backend_http
          codec_type: AUTO
          route_config:
            name: backend_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "ok\\n"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: local_backend
    connect_timeout: 1s
    type: STATIC
    load_assignment:
      cluster_name: local_backend
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 19000

admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
"""
        args.out_envoy.parent.mkdir(parents=True, exist_ok=True)
        args.out_envoy.write_text(yaml, encoding="utf-8")
        print(f"Wrote Envoy YAML -> {args.out_envoy}", file=sys.stderr)

    if not args.out_json and not args.out_envoy:
        print(plugin_json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
